baseURL = "https://docs.configset.com/"
title = "CFS Documentation"
themesDir = "themes"
theme = "hugo-theme-learn"
defaultContentLanguage = "en"
enableEmoji = true

[params]
  editURL = "https://github.com/configset/cfs-docs/edit/main/content/"

[[menu.main]]
  identifier = "docs"
  name = "Docs"
  title = "Documentation"
  url = "/docs/"
  weight = 10

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
