baseURL = "https://docs.configset.com/"
title = "CFS Documentation"
theme = "slate"
defaultContentLanguage = "en"
enableEmoji = true

[params]
  editURL = "https://github.com/configset/cfs-docs/edit/main/content/"

[[menu.main]]
  identifier = "docs"
  name = "Docs"
  title = "Documentation"
  url = "/docs/"
  weight = 10
