baseURL = "https://docs.brucedom.com/"
title = "CFS Documentation"
themesDir = "themes"
theme = "hugo-theme-learn"
defaultContentLanguage = "en"
enableEmoji = true

[params]
  editURL = "https://github.com/bruce/bruce-docs/edit/main/content/"
  themeVariant = "blue"

[[menu.main]]
  identifier = "docs"
  name = "Docs"
  title = "Documentation"
  url = "/docs/"
  weight = 10

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
